# Generated by Django 6.0.3 on 2026-06-06 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0003_flatmateinquiry'),
        ('rooms', '0008_savedflatmate'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='flatmate_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='rooms.flatmateprofile'),
        ),
    ]
