# Generated by Django 6.0.2 on 2026-04-09 15:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon', models.CharField(help_text='Emoji ya Icon class', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('city', models.CharField(choices=[('Bangalore', 'Bangalore'), ('Mumbai', 'Mumbai'), ('Delhi', 'Delhi'), ('Patna', 'Patna')], max_length=50)),
                ('area', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('room_type', models.CharField(choices=[('Private Room', 'Private Room'), ('Shared Room', 'Shared Room'), ('Studio', 'Studio / 1BHK'), ('Master Bedroom', 'Master Bedroom')], max_length=50)),
                ('bhk_config', models.CharField(default='1 BHK', max_length=20)),
                ('floor', models.CharField(max_length=50)),
                ('available_from', models.DateField()),
                ('min_stay', models.CharField(max_length=50)),
                ('rent', models.IntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(80000)])),
                ('deposit', models.CharField(max_length=50)),
                ('maintenance', models.CharField(max_length=50)),
                ('furnishing_status', models.CharField(choices=[('Fully', 'Fully Furnished'), ('Semi', 'Semi Furnished'), ('Unfurnished', 'Unfurnished')], max_length=20)),
                ('description', models.TextField(max_length=400)),
                ('house_rules', models.TextField(blank=True)),
                ('nearest_metro', models.CharField(blank=True, max_length=100)),
                ('distance_to_hub', models.CharField(blank=True, max_length=100)),
                ('pref_gender', models.CharField(choices=[('Any', 'Any'), ('Male', 'Male only'), ('Female', 'Female only')], default='Any', max_length=10)),
                ('pref_occupation', models.CharField(default='Any', max_length=50)),
                ('sleep_schedule', models.CharField(default='No preference', max_length=50)),
                ('cleanliness_level', models.IntegerField(default=7, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('guest_policy', models.CharField(default='Occasional guests OK', max_length=100)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amenities', models.ManyToManyField(blank=True, to='rooms.amenity')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='listings/')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rooms.listing')),
            ],
        ),
    ]
