# Generated by Django 6.0.2 on 2026-04-10 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='included_cooking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='included_electricity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='included_gas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='included_housekeeping',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='included_water',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='included_wifi',
            field=models.BooleanField(default=False),
        ),
    ]
