# Generated by Django 6.0.3 on 2026-04-15 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_listing_contact_email_listing_contact_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Saved_Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='rooms.listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_rooms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved Room',
                'verbose_name_plural': 'Saved Rooms',
                'unique_together': {('user', 'room')},
            },
        ),
    ]
