# Generated by Django 6.0.3 on 2026-04-15 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_saved_rooms'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saved_rooms',
            options={},
        ),
    ]
