# Generated by Django 6.0.3 on 2026-05-10 03:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlatmateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(45)])),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Non-binary', 'Non-binary'), ('Prefer not to say', 'Prefer not to say')], max_length=20)),
                ('occupation', models.CharField(choices=[('Student', 'Student'), ('Software / IT', 'Software / IT'), ('Corporate Professional', 'Corporate Professional'), ('Freelancer', 'Freelancer'), ('Healthcare', 'Healthcare'), ('Startup', 'Startup'), ('Research / Academia', 'Research / Academia'), ('Creative / Media', 'Creative / Media'), ('Other', 'Other')], max_length=50)),
                ('city', models.CharField(choices=[('Bangalore', 'Bangalore'), ('Mumbai', 'Mumbai'), ('Delhi', 'Delhi'), ('Hyderabad', 'Hyderabad'), ('Pune', 'Pune'), ('Chennai', 'Chennai'), ('Kolkata', 'Kolkata'), ('Patna', 'Patna')], max_length=50)),
                ('preferred_area', models.CharField(blank=True, max_length=100)),
                ('language_pref', models.CharField(blank=True, choices=[('Hindi', 'Hindi'), ('English', 'English'), ('Hindi+English', 'Hindi + English'), ('Any', 'Any')], max_length=50)),
                ('bio', models.TextField(blank=True, max_length=300)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='flatmates/')),
                ('max_budget', models.IntegerField(default=12000)),
                ('room_type_pref', models.CharField(default='Any', max_length=50)),
                ('move_in', models.CharField(default='Flexible', max_length=50)),
                ('stay_duration', models.CharField(default='Flexible', max_length=50)),
                ('interest_tags', models.TextField(blank=True)),
                ('sleep_schedule', models.CharField(default='No Preference', max_length=50)),
                ('cleanliness_level', models.IntegerField(default=7, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('noise_tolerance', models.CharField(default='Moderate OK', max_length=50)),
                ('guest_policy', models.CharField(default='Occasional OK', max_length=100)),
                ('work_style', models.CharField(default='Hybrid', max_length=50)),
                ('smoking', models.CharField(default='Non-smoker', max_length=50)),
                ('alcohol', models.CharField(default="Don't drink", max_length=50)),
                ('pets', models.CharField(default='No pets', max_length=50)),
                ('pref_gender', models.CharField(default='Any', max_length=20)),
                ('pref_age_range', models.CharField(default='Any', max_length=50)),
                ('pref_occupation', models.CharField(default='Any', max_length=50)),
                ('flatmate_expectation', models.TextField(blank=True, max_length=400)),
                ('contact_phone', models.CharField(max_length=20)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_preference', models.CharField(default='WhatsApp', max_length=50)),
                ('contact_visibility', models.CharField(default='Show after connect only', max_length=50)),
                ('vibe_score', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='flatmate_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-vibe_score', '-created_at'],
            },
        ),
    ]
