# Generated by Django 6.0.3 on 2026-06-10 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_savedflatmate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flatmateprofile',
            options={},
        ),
    ]
