# Generated by Django 6.0.3 on 2026-06-10 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0009_alter_flatmateprofile_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flatmateprofile',
            options={'ordering': ['-vibe_score', '-created_at']},
        ),
    ]
