# Generated by Django 6.0.3 on 2026-06-25 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0010_alter_flatmateprofile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='inquiry_count',
            field=models.IntegerField(default=0),
        ),
    ]
