# Generated by Django 6.0.3 on 2026-06-25 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0011_listing_inquiry_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flatmateprofile',
            name='city',
            field=models.CharField(choices=[('Bangalore', 'Bangalore'), ('Mumbai', 'Mumbai'), ('Delhi', 'Delhi'), ('Hyderabad', 'Hyderabad'), ('Pune', 'Pune'), ('Chennai', 'Chennai'), ('Kolkata', 'Kolkata'), ('Noida', 'Noida'), ('Gurgaon', 'Gurgaon')], max_length=50),
        ),
        migrations.AlterField(
            model_name='listing',
            name='city',
            field=models.CharField(choices=[('Bangalore', 'Bangalore'), ('Mumbai', 'Mumbai'), ('Delhi', 'Delhi'), ('Hyderabad', 'Hyderabad'), ('Pune', 'Pune'), ('Chennai', 'Chennai'), ('Kolkata', 'Kolkata'), ('Noida', 'Noida'), ('Gurgaon', 'Gurgaon')], max_length=50),
        ),
        migrations.AlterField(
            model_name='listing',
            name='room_type',
            field=models.CharField(choices=[('Private Room', 'Private Room'), ('Shared Room', 'Shared Room'), ('Studio', 'Studio / 1BHK'), ('PG', 'PG / Hostel')], max_length=50),
        ),
    ]
