# Generated by Django 6.0.3 on 2026-06-29 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0012_alter_flatmateprofile_city_alter_listing_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flatmateprofile',
            name='role',
            field=models.CharField(choices=[('needs_room', 'Needs a Room'), ('has_room', 'Has a Room')], default='needs_room', max_length=20),
        ),
    ]
