# Generated by Django 6.0.3 on 2026-03-31 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profession',
            field=models.CharField(default='Software Engineer', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='vibe_score',
            field=models.IntegerField(default=0),
        ),
    ]
