# Generated by Django 6.0.3 on 2026-04-14 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_name_profile_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='personality_tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
