# Generated by Django 6.0.3 on 2026-05-06 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_flatmateprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FlatmateProfile',
        ),
    ]
